name: OctocatApp CI

on: [push, pull_request]

jobs:
  init:
    name: Initiate pipeline
    runs-on: windows-latest
    # defaults:
    #   run:
    #     shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: 
          fetch-depth: 50 

      - run: echo "${{ github.repository_owner }}_${{ github.event.repository.name }}"


      - name: Lowercase gen
        id: lowercase_gen
        run: |
          $LOWERCASE_OWNER = "${{ github.repository_owner }}".ToLower()
          echo "::set-output name=owner_name::$LOWERCASE_OWNER"

      - run: echo "${{ steps.lowercase_gen.outputs.owner_name }}"



      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
          
      - name: Initialize SonarCloud scanner
        id: init_sonar_scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: .\.sonar\scanner\dotnet-sonarscanner begin /k:"${{ github.repository_owner }}_${{ github.event.repository.name }}" /o:"${{ steps.lowercase_string_gen.outputs.owner_name }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"  
          
      - run: dotnet build
          
      - name: Send SonarCloud results
        id: send_sonar_results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"





      # - name: Bump release version and create release tag
      #   id: tag_generator
      #   uses: mathieudutour/github-tag-action@v5
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     default_bump: false 



      # - name: Publish NuGet package
      #   id: publish_nuget
      #   uses: rohith/publish-nuget@v2
      #   continue-on-error: true
      #   with:
      #       PROJECT_FILE_PATH: OctocatApp.csproj
      #       TAG_COMMIT: true
      #       NUGET_KEY: ${{secrets.TEST_PKG}}
      #       PACKAGE_NAME: OctocatApp-testpkg

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ steps.tag_generator.outputs.new_tag }}
      #     release_name: Release ${{ steps.tag_generator.outputs.new_tag }}
      #     body: '[CHANGE LOG](HISTORY.md)'

      # - name: Upload Release Asset
      #   id: upload_release_asset
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: OctocatApp.csproj
      #     asset_name: OctocatApp.${{ steps.tag_generator.outputs.new_version }}.csproj
      #     asset_content_type: application/csproj

      # - name: Upload Release Asset
      #   id: upload_release_asset2
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: OctocatApp.sln
      #     asset_name: OctocatApp.${{ steps.tag_generator.outputs.new_tag }}.sln
      #     asset_content_type: application/sln

      # - name: Upload Release Asset
      #   id: upload_release_asset3
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: Program.cs
      #     asset_name: Program.${{ steps.tag_generator.outputs.new_tag }}.cs
      #     asset_content_type: application/cs
