on: push

name: OctocatApp CI

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bump version and push tag
        uses: ChloePlanet/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.github-tag-action.outputs.new_tag }} # ${{ github.ref }}
          release_name: ${{ steps.github-tag-action.outputs.new_tag }} # ${{ github.ref }}
          body: |
            Changes in this Release
            - First Changes
          draft: false
          prerelease: false

